Add unfinished lab 1
cakesonia/mobile_dev pull request #1
Opened 2019-09-25 10:24 UTC by cakesonia

2019-10-13 14:58 UTC, nvipash requested changes
### First review of Laboratory work №1

General comments:
- uncorrect .gitignore, committed .idea
- public modifier of the methods that should be private
- some too long methods and lines
- remove Log usage
- all strings should be in strings.xml

2019-10-13 14:58 UTC, nvipash commented on app/.gitignore
> +/build
зайвий .gitignore

2019-10-13 14:58 UTC, nvipash commented on .gitignore
> +/.idea/assetWizardSettings.xml
де ви берете усі той .gitignore, що так неправильно оформлений😶 для папок не варто писати / - попереду

2019-10-13 14:58 UTC, nvipash commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
тести нам не будуть потрібні, прибери їх будь ласка з dependencies

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +                signIn(txtInputEmail.getEditableText().toString().trim(), txtInputPassword.getEditableText().toString().trim());
я би повиносив ці витягування з полей у окремі змінні, бо задовга стрічка виходить;

все що в onClick варто винести в окремий метод і потім викликати його тут, щоб скоротити об'єм onCreate

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +                            Log.d(TAG, "signInWithEmail:success");
Log'и не варто commit'ати

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +                            Log.w(TAG, "signInWithEmail:failure", task.getException());
same

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +    public void openSignUp(View view) {
цей метод не використовується

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +    private static final String TAG = "SignInActivity";
TAG для log'ів, як і логи його варто прибрати

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +    public void openWelcome() {
чомусь усі власні методи public

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +            txtInputEmail.setError("Invalid email");
усі стрічки варто винести в strings.xml

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignUpActivity.java
> +                        txtInputPassword.getEditableText().toString().trim());
[2] я би повиносив ці витягування з полей у окремі змінні, бо задовга стрічка виходить;

все що в onClick варто винести в окремий метод і потім викликати його тут, щоб скоротити об'єм onCreate

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignUpActivity.java
> +    public void openSignIn(View view) {
цей метод теж не використовується

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignUpActivity.java
> +
зайва пуста стрічка

2019-10-13 14:58 UTC, nvipash commented on app/src/main/res/values/colors.xml
> +    <color name="colorSecondaryDark">#9ea7aa</color>-->
закоментований код

2019-10-13 14:58 UTC, nvipash commented on app/src/main/res/values/strings.xml
> +    <string name="sign_out">Sign out</string>
тут не всі стрічки

2019-10-13 14:58 UTC, nvipash commented on app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
цей плагін варто зберігати зверху поряд з `apply plugin: 'com.android.application'`

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignUpActivity.java
> +    private static final String TAG = "SignUpActivity";
same as in SignInActivity

2019-10-13 14:58 UTC, nvipash commented on app/src/main/java/com/example/lab1/SignUpActivity.java
> +                    });
цю частину я би виніс у окремий `private void updateProfile()`, щоб скоротити `setUserName()`

2019-10-17 06:29 UTC, cakesonia commented on app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
гайд файєрбейзу казав зберiгати в кінці файлу)

2019-10-17 06:33 UTC, cakesonia commented on .gitignore
> +/.idea/assetWizardSettings.xml
та він згенерований)

2019-10-17 06:52 UTC, cakesonia commented on app/src/main/java/com/example/lab1/SignInActivity.java
> +    public void openSignUp(View view) {
@nvipash він викликається у activity_sign_in.xml `android:onClick="openSignUp"` 62 рядок

2019-10-17 07:07 UTC, cakesonia commented on app/src/main/java/com/example/lab1/SignUpActivity.java
> +    public void openSignIn(View view) {
the same: activity_sign_up.xml - 89 line - `android:onClick="openSignIn"`

2019-10-17 10:03 UTC, merged